apiVersion: apps/v1
kind: Deployment
metadata:
  name: game2048-by-abderrahman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game2048
  template:
    metadata:
      labels:
        app: game2048
    spec:
      containers:
      - name: game2048-container
        image: blackicebird/2048
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

